name: imsproject

networks:
  ims-network:
    name: ims-network
    driver: bridge

services:

  ims-game-server:
    image: yuvalroth123/imsproject_game_server:latest
    container_name: ims-game-server
    networks:
      - ims-network
    ports:
        - "8080:8080"
        - "8641:8641/udp"
    volumes:
        - /home/admin/volumes/game_server:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: /home/admin/env_files/db_credentials.env

  ims-manager:
    image: yuvalroth123/imsproject_manager:latest
    container_name: ims-manager
    networks:
      - ims-network
    ports:
      - "5000:5000"
    volumes:
      - /home/admin/volumes/manager:/app/data

  ims-db:
    image: postgres:latest
    container_name: ims-db
    environment:
      POSTGRES_DB: ims-db
    ports:
      - "5432:5432"
    networks:
      - ims-network
    volumes:
      - /home/admin/volumes/db/data:/var/lib/postgresql/data
      - /home/admin/volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/admin/volumes/db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - /home/admin/volumes/db/certs/server.crt:/var/lib/postgresql/server.crt:ro
      - /home/admin/volumes/db/certs/server.key:/var/lib/postgresql/server.key:ro
    env_file: /home/admin/env_files/db_credentials.env
