name: imsproject

networks:
  ims-network:
    name: ims-network
    driver: bridge

services:

  ims-game-server:
    image: yuvalroth123/imsproject_game_server:latest
    container_name: ims-game-server
    networks:
      - ims-network
    ports:
        - "8080:8080"
        - "8641:8641/udp"
    volumes:
        - /home/admin/volumes/game_server:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ims-manager:
    image: yuvalroth123/imsproject_manager:latest
    container_name: ims-manager
    networks:
      - ims-network
    ports:
      - "5000:5000"
    volumes:
      - /home/admin/volumes/manager:/app/data

  ims-db:
    image: postgres:latest
    container_name: ims-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminMTAC
      POSTGRES_DB: ims-db
    ports:
      - "5432:5432"
    networks:
      - ims-network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql #local
      - ./database/data:/var/lib/postgresql/data #local
#      - /home/admin/volumes/db_server/data:/var/lib/postgresql/data #remote
#      - /home/admin/volumes/db_server/init.sql:/docker-entrypoint-initdb.d/init.sql #remote
