name: imsproject

networks:
  ims-network:
    name: ims-network
    driver: bridge

services:

  ims-game-server:
    image: yuvalroth123/imsproject_game_server:latest
    container_name: ims-game-server
    networks:
      - ims-network
    ports:
        - "8640:8640"
        - "8641:8641/udp"
    volumes:
        - /home/admin/volumes/game_server:/app/data
        - /etc/letsencrypt/live/ims-project.cs.bgu.ac.il:/app/certificates

  ims-manager:
    image: yuvalroth123/imsproject_manager:latest
    container_name: ims-manager
    networks:
      - ims-network
    ports:
      - "5000:5000"
    volumes:
      - /home/admin/volumes/manager:/app/data
      - /etc/letsencrypt/live/ims-project.cs.bgu.ac.il:/app/certificates